### ISSUE TITLE
Cop / Independend

### ISSUE THREAD

**Issue by coresync2k** [DiabolicaTrix/Life-Banking-System#4]
Hey,
On CIV Side all is working, but if you login as COP or INDEP, you must set every login/spawn the pin.
He is correct set into Database, but it is not working with the COP / Indep Side.

**Comment by Stacced** [comment]
You should take a look in your querys, maybe it's not selecting banking_pin correctly.

**Comment by DiabolicaTrix** [comment]
Try downloading the new version.

**Comment by coresync2k** [comment]
yes i have fixxed it, with the changes you have implemented.
